try {
    hello();
} catch (error) {
    console.log(error);
}

try {

} catch {
    
}